name: Deploy Learning Dashboard

on:
  workflow_run:
    workflows: ["Python CI Pipeline"]
    types:
      - completed

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    environment:
      name: github-pages

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: Docs

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4